### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by martsklav** [mikeyy/nonoCAPTCHA#25]
Hey, i have got not only an error, but 2!

First error :

`Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from nonocaptcha import Settings
ImportError: cannot import name 'Settings'
`

I tried fixing this one by adding .base to nonocaptcha from 
`from nonocaptcha import settings`
 to 
`from nonocaptcha.base import settings`, 
this resulted in the second error:

`Traceback (most recent call last):
  File "main.py", line 7, in <module>
    pageurl = settings["run", "http://url.com/"]
KeyError: ('run', 'http://url.com/')
`

I realise the second error might be absolutely useless, i do not get the first one tho.
Let me know if i need to send anything else.

**Comment by mikeyy** [comment]
I've pushed a now working usage code. Thanks for catching that for me!

**Comment by martsklav** [comment]
Thanks! It works now, imma close.
