### ISSUE TITLE
Unable to click on checkbox

### ISSUE THREAD

**Issue by frosty00** [mikeyy/nonoCAPTCHA#26]
Just wondering which version of chromium you are using, since I am getting bugs on the current release.

```
2018-08-10 14:28:21,181 0 Starting solver with proxy None
2018-08-10 14:28:21,189 0 Protocol Error: 'Page.setBypassCSP' wasn't found None <class 'pyppeteer.errors.NetworkError'>
2018-08-10 14:28:21,218 0 Browser closed
```

I fixed this by commenting out the Page.setBypassCSP code. However the code cannot click on the I am a robot checkbox and it only becomes grey out a bit but never fully checked and becomes stuck at:

```
2018-08-10 14:29:50,343 0 Starting solver with proxy None
2018-08-10 14:29:52,742 0 Clicking checkbox
```

What browser are you using?
I am using Chromium Version 67.0.3372.0 (Developer Build) (64-bit) for mac that was installed by default by pyppeteer

**Comment by mikeyy** [comment]
Seems like pyppeteer didn't upgrade alongside nonocaptcha. Check if version==0.0.19 is installed. And I recommend running python -c "import pyppeteer"  afterward to download the browser.

Heads up, 0.0.20 was released very recently and I haven't had the opportunity to properly test it. Quite frankly I'm not even sure if it ships with a new browser release!

**Comment by frosty00** [comment]
Hi,

Could you send me a working pritini config so I can run the library and even make commits. 

Thanks again,

Carlo

**Comment by mikeyy** [comment]
Pritunl should work now. Docker failed to start the container after a server reboot.

Are there any errors that follow "Downloading audio file"? Please verify the settings and those dependencies for the designated speech-to-text service are all met. I'll create an individual file for testing speech-to-text functionality in future cases, and improve on messages produced during debugging. May even consider adding additional checks for service configuration on script startup.

**Comment by mikeyy** [comment]
I've also considered removing both Bing and Amazon. My reason for each follows. The cost for using Bing is considerably more expensive than using if you were to use a third-party solving service. Even though my usage through Amazon was inextensive, each request had around a response time of 60 seconds, if not more. My plans are to completely localize nonoCAPTCHA. At least for now, Iike to determine accuracy while using DeepSpeech and PocketSphinx before moving forward.

**Comment by frosty00** [comment]
I ran the script again today, and managed to connect to the proxies this time.

I’m still using the three back connect proxies you sent me before, but I am unable to click on the audio button now. I ran the script for ~ 10 minutes and was unsuccessful in getting even one hit (option to download the audio without being banned).

> 80.93.90.84:3001
> 80.93.90.27:3001
> 80.93.90.69:3001

I think my previous issue was due to my free trial with Azure expiring so I will look at installing the other speech to text dependencies. 

Any thoughts as to why those proxies are banned? Also the ProxyDB model does not work with backconnect proxies since it stores the ip and port as the key in the database, however one backconnect proxy may map to multiple ips.

I think we will have more success with image analysis so that's what I’m going to work on.

**Comment by mikeyy** [comment]
My apologies for the delay.

Did you have any success navigating to the audio portion without being blocked?

The persistent blocking can be attributed to using only three proxies and that rotation only occurs when a proxy is considered dead. Supplying you with more proxies would increase your chances of finding a non-blocked proxy. But being able to rotate to another proxy on command may prove more useful though. Keeping in mind, all without having to provide my full list of proxies.

> Also the ProxyDB model does not work with backconnect proxies since it stores the ip and port as the key in the database, however one backconnect proxy may map to multiple ips.

You have a point and I've been planning on making adjustments since your last concern was raised.

> I think we will have more success with image analysis so that's what I’m going to work on.

Can't wait to see this in action. Good luck, let me know if you need any help.
