### ISSUE TITLE
Can you send me a new prituni address

### ISSUE THREAD

**Issue by frosty00** [mikeyy/nonoCAPTCHA#28]
Looking to work on this project again, but would like a proxy to use. 

Feel free to email me. 

Many thanks,
Carlo

**Comment by frosty00** [comment]
So just from looking at the code I can see we have updated to pyppeeteer 0.0.21

New exceptions have been added:

```
(SafePassage, ButtonError, DefaceError, PageError, nonocaptchaError)
```

These are all pretty self explainitory except for `SafePassage`, is this error supposed to help distinguish between when to solve audio vs solve image? 

Are the design goals still the same as the flowchart I posted [here]

**Comment by mikeyy** [comment]
Hey, due to some unfortunate circumstances, I've been unable to afford the usual proxies for this month. I've been researching other services and may have found a feasible alternative that fits my budget. However, my server is also due for this month and makes it difficult for me to make ends meet. Trying to come up with a solution but almost running out of ideas.

**Comment by mikeyy** [comment]
> These are all pretty self explainitory except for SafePassage, is this error supposed to help distinguish between when to solve audio vs solve image?

Correct, SafePassage is just an exception that's raised when Base.check_detection times-out. Considering Base.check_detection evaluates a variety of Javascript elements, it seemed the most reasonable at the time. A change in logic is planned.

**Comment by frosty00** [comment]
No worries at all, we can continue to work on the image solving part for now since they typically take longer to ban image attempts and rarely block on the first checkbox. 

I currently have a server and I think I have access to the servers at Berkeley for free so I will investigate that also and get back to you. 

Perhaps you could downgrade to less proxies if possible? 

Anyways, I appreciate all the work you have done on the library.

**Comment by mikeyy** [comment]
Yeah, blocking from images is rare, at most it'll require you to solve additional.

I'm open to practical alternatives. Lately, I've been using a 20 cores/40 thread server for testing the solver at high loads (around 150 Chrome instances).

The proxy provider I'm considering gives a choice for how many proxies to purchase. I won't have 50,000 proxies to rotate through, but I'll have to make it work.

Thank you, I don't plan on quitting anytime soon, there is much work to be had. 👍

**Comment by BenBaltz** [comment]
Smartproxy works pretty good with XEvil recaptcha solving

**Comment by frosty00** [comment]
@BenBaltz url to smartproxy?

**Comment by BenBaltz** [comment]
smartproxy.io I believe, it's expensive but very high quality USA residential

**Comment by BenBaltz** [comment]
I'd be willing to pay $.75-1 per 1k recap if you guys had this working consistently.

**Comment by mikeyy** [comment]
> Smartproxy works pretty good with XEvil recaptcha solving

Awesome, I'm looking into them now. I wonder how long 5GB would last.

My other choice was https://blazingseollc.com/

**Comment by frosty00** [comment]
> I'd be willing to pay $.75-1 per 1k recap if you guys had this working consistently.

I think there are already sites that do sell recaptchas via API, however the better solution would be to  integrate it into your own code for *free*

**Comment by BenBaltz** [comment]
@frosty00 this has never worked reliably on either of my machines.

**Comment by mikeyy** [comment]
> I'd be willing to pay $.75-1 per 1k recap if you guys had this working consistently.

That was my introductory price once I had a service running, so I could make all the other competitors dry. After initial runs, and considering it profitable I may leave it at 1$. 

> I think there are already sites that do sell recaptchas via API, however the better solution would be to integrate it into your own code for free

There are but they charge upwards of $3.00 per 1000

**Comment by BenBaltz** [comment]
other sites selling recaptcha right now are very expensive or too slow.

**Comment by BenBaltz** [comment]
@mikeyy blazing is data center i thought

**Comment by mikeyy** [comment]
> @mikeyy blazing is data center i thought

They have residential rotating as well.

**Comment by mikeyy** [comment]
I purchased the micro plan from SmartProxy, and initial results are promising. Unsure how long 5GB will last though. Now to figure out the server ordeal...

Thanks @BenBaltz

**Comment by mikeyy** [comment]
Finally ran an overnight test with the 5GB plan and consumed the bandwidth after 200 successful solves. Despite the services ability to reach the audio part regularly, they are too expensive for this task.

**Comment by mikeyy** [comment]
Closing this issue, feel free to reopen.
