### ISSUE TITLE
Unable to copy files in Dockerfile

### ISSUE THREAD

**Issue by mikeyy** [mikeyy/nonoCAPTCHA#33]
I'm experiencing an issue copying files from an absolute folder on a host machine to a docker container. I'm looking for anyone with experience with setting up a Dockerfile who can help out or lend some advice on what I'm doing incorrectly. I already have a Dockerfile in the root Repo, and the files I'm trying to copy over are already in place, except it doesn't work.

**Comment by Thomanphan** [comment]
Do you try this
https://stackoverflow.com/questions/22907231/copying-files-from-host-to-docker-container

**Comment by mikeyy** [comment]
Thanks for the link, I'll look over it.
