### ISSUE TITLE
Headless is being detected by Google

### ISSUE THREAD

**Issue by mikeyy** [mikeyy/nonoCAPTCHA#34]
During my testing, I've become aware of an issue where headless is being detected as automation while not headless proceeds to the audio step with no problems. Looking for the culprit and will release an update.

**Comment by BenBaltz** [comment]
https://antoinevastel.com/bot%20detection/2018/01/17/detect-chrome-headless-v2.html

**Comment by BenBaltz** [comment]
Maybe window.chrome missing?

**Comment by mikeyy** [comment]
Perhaps this could be a simple mixup and there are no issues. Just wanted to make a notice if anyone else is having problems, headless compared to not headless.

**Comment by mikeyy** [comment]
> https://antoinevastel.com/bot%20detection/2018/01/17/detect-chrome-headless-v2.html



> Maybe window.chrome missing?

In the past, their main detection methods were "window.navigator.webdriver", which I've accounted for on line 160 of solver.py, https://github.com/mikeyy/nonoCAPTCHA/blob/master/nonocaptcha/solver.py#L160

Window.chrome shouldn't be missing considering we are usually the actual browser and not a javascript knockoff. Will run through and double check everything. This will be a pain in headless.

**Comment by BenBaltz** [comment]
https://intoli.com/blog/making-chrome-headless-undetectable/

**Comment by mikeyy** [comment]
Haven't been able to work on the script at all these past few days, hoping to have some free time this week for routine testing and addressing other issues.

**Comment by mikeyy** [comment]
Not able to confirm beyond speculation at this time. Something is triggering the bot detection yet not always. Closing this issue until further notice.
