### ISSUE TITLE
Detected

### ISSUE THREAD

**Issue by Eastkap** [mikeyy/nonoCAPTCHA#37]
Status always is detected, using with and without proxies, probably more flags to add to pyppeteer ?

**Comment by mikeyy** [comment]
Have been unable to maintain detection evasion due to lack of funding for proxies. Data center proxies will not work. Are you using premium proxies, preferably residential?

**Comment by Eastkap** [comment]
Yes, maybe we can speak privately?

(wow that answer time by the way)

**Comment by mikeyy** [comment]
Yes, you can email me at mikeyy@mikeyy.com.

**Comment by Eastkap** [comment]
@Thomanphan seems like it's more due to some flag we're missing when launching the headed instance or some JS not properly being executed that leads to the automation detection.

I was able to chat with @mikeyy and he sent me a gif of him executing the code with no issue. My guess is he has some option/ different set-up than the one in the latest commit available.
![image](https://user-images.githubusercontent.com/2210144/47705401-bb0f2500-dc26-11e8-806d-4a4fbf3d9c58.png)

**Comment by keitarodotnet** [comment]
I am facing the same problem.
Please let me know if you need an option at execute.

**Comment by mikeyy** [comment]
I recommend trying a different reCAPTCHA source other than testing with the default reCAPTCHA demo page. That page is on high-security it seems, and blocks a high-majority of requests.
