### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'SafeChildWatcher'

### ISSUE THREAD

**Issue by articlefr** [mikeyy/nonoCAPTCHA#40]
I installed all requirements and runned "python app.py" but it returned with this error message "AttributeError: module 'asyncio' has no attribute 'SafeChildWatcher'".

Please help!

**Comment by mikeyy** [comment]
Try now

**Comment by articlefr** [comment]
NOPE I GOT THIS ERROR BELOW:

C:\nonocaptcha\examples>python app.py
Traceback (most recent call last):
  File "app.py", line 40, in <module>
    asyncio.get_child_watcher().attach_loop(parent_loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 767, in get_child_watcher
    return get_event_loop_policy().get_child_watcher()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 603, in get_child_watcher
    raise NotImplementedError
NotImplementedError

**Comment by articlefr** [comment]
Well any updates?

**Comment by mikeyy** [comment]
Latest update worked on my Windows virtual machine. Try it now.

**Comment by articlefr** [comment]
It's working... 

How do I call it from the web? 

And also importantly want proxies work for this so it wont get the Google page error when clicking the audio button to download the audio.mp3 file?

Thanks!

**Comment by mikeyy** [comment]
Yes, proxy support is available. The Solver class accepts two arguments, proxy and proxy_auth, for setting a proxy. I have a basic function for loading/file with proxies every so minutes in a couple of the included examples, app.py being one of them.

The default address is http://127.0.0.1:5000 if using app.py example

**Comment by articlefr** [comment]
I have been gettn
