### ISSUE TITLE
HOW CAN I SOLVE THIS PROBLEM???

### ISSUE THREAD

**Issue by sokungamemaster** [mikeyy/nonoCAPTCHA#8]
$ pip3 install nonocaptcha
Collecting nonocaptcha
  Using cached https://files.pythonhosted.org/packages/62/ca/1d7b8da26c8a994e49d74bc1521a64ec7e740b70bd04ba711cc78f079b3a/nonocaptcha-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-GmLmCS/nonocaptcha/setup.py", line 3, in <module>
        from importlib.machinery import SourceFileLoader
    ImportError: No module named machinery
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-GmLmCS/nonocaptcha/

**Comment by mikeyy** [comment]
Hello, what version of Python are you using? I believe importlib.machinery wasn't added until Python 3.3. Type this into console:

``python3 --version
``

**Comment by sokungamemaster** [comment]
I'm currently using Python 3.6.6rc1+

**Comment by mikeyy** [comment]
Dang, seems like importlib.machinery was deprecated on 3.6.6. I'll apply a patch here in a bit and upload it to PyPI and report back here.

**Comment by mikeyy** [comment]
Nearest version I could install on my system was 3.7.0b3 but I didn't run into the import issue and it did install fully. Though it didn't run the Chrome automation at all, for some reason. Is there any chance you could install 3.6.5 on your system and report back here?

I'm going to have to update the Requirements section on the project to only support 3.6.5 until I can fully vet all other versions.

Sorry for any inconvenience this may have caused.

**Comment by mikeyy** [comment]
Closing this issue.
